
server:
  port: 9001

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:sqlserver://host.docker.internal:1433;encrypt=true;trustServerCertificate=true;databaseName=ProductDB
    username: SA
    password: Prince@10
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
eureka:
  instance:
    hostname: ${POD_NAME}.eureka
    prefer-ip-address: false 
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE_URL:http://localhost:8761/eureka}

EUREKA_DEFAULTZONE_URL: http://${eureka.instance.hostname}:8761/eureka




